server:
  port: 8082

spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        # 向服务注册中心注册该服务,确保服务注册中心存活
        server-addr: localhost:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'

